server:
  port: 8888
spring:
  application:
    name: LAIGOU-PRODUCT #服务名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/laigou-product?useUnicode=true&characterEncoding=utf-8useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: xf1234
#配置mapperxml文件的位置
mybatis-plus:
  mapper-locations: classpath*:cn/itsource/laigou/mapper/*Mapper.xml

  