server:
  port: 6666
spring:
  application:
    name:LAIGOU-PLAT

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://root:xf1234@localhost:8761/eureka/ //eureka地址

