server:
  port: 8888
spring:
  application:
    name: LAIGOU-PRODUCT #服务名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url=jdbc:mysql://172.16.4.106/laigou-product?useUnicode=true&characterEncoding=utf8
    username: root
    password: xf1234
#配置mapperxml文件的位置
mybatis-plus:
  mapper-locations: classpath*:cn/itsource/laigou/mapper/*Mapper.xml

  